name: Android CI

on:
  push:
    branches: [ master ]
    paths:
      - 'android/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'android/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Build with Gradle
      run: |
        cd android
        ./gradlew build
        
    - name: Run Android Tests
      run: |
        cd android
        ./gradlew test
        
    - name: Build Release APK
      if: github.ref == 'refs/heads/master'
      run: |
        cd android
        ./gradlew assembleRelease
        
    - name: Sign Android Release
      if: github.ref == 'refs/heads/master'
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: android/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        
    - name: Upload APK
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release-signed.apk
        
    - name: Create Release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: android/app/build/outputs/apk/release/app-release-signed.apk
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
